python scripts/run_ne_analysis.py \
    --species-autosomes data/species_autosomes.vcf.gz \
    --species-x data/species_x.vcf.gz \
    --species-y data/species_y.vcf.gz \
    --species-mt data/species_mt.vcf.gz \
    --outgroup-autosomes data/outgroup_autosomes.vcf.gz \
    --outgroup-x data/outgroup_x.vcf.gz \
    --outgroup-y data/outgroup_y.vcf.gz \
    --outgroup-mt data/outgroup_mt.vcf.gz \
    --output results.json \
    --verbose